name: Build Application

on:
    push:
        branches:
            - publish # Trigger build on pushes to the publish branch
    pull_request:
        branches:
            - publish # Trigger build on pull requests to the publish branch

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12 # Replace with the Python version you need

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run build script
              run: python build.py

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v3
              with:
                  name: windows-build
                  path: dist/Presence\ Maker.exe # Adjust if your output path differs

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12 # Replace with the Python version you need

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run build script
              run: python3 build.py

            - name: Make executable
              run: chmod +x dist/Presence\ Maker # Ensure the file is executable

            - name: Upload Linux artifact
              uses: actions/upload-artifact@v3
              with:
                  name: linux-build
                  path: dist/Presence\ Maker # Adjust if your output path differs

    build-macos:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12 # Replace with the Python version you need

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run build script
              run: python3 build.py

            - name: Make executable
              run: chmod +x dist/Presence\ Maker # Ensure the file is executable

            - name: Upload macOS artifact
              uses: actions/upload-artifact@v3
              with:
                  name: macos-build
                  path: dist/Presence\ Maker # Adjust if your output path differs
